version: '3.9'

services:
  jwt-user-auth:
    build: .
    container_name: jwt-ms
    image: jwt-microservice
    ports:
      - "8080:8080"
    environment:
      - db-url=jdbc:postgresql://db:5432/central_database
      - db-username=postgres
      - db-password=postgres
    depends_on:
      - db
    restart: always

  db:
    ports:
      - "5432:5432"
    container_name: postgres-central-db
    image: postgres:12
    environment:
      - POSTGRES_DB=central_database
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - /var/lib/docker/volumes/auth-ms-volume/_data:/var/lib/postgresql/data
    restart: always

networks:
  default:
    name: app-ms
    external: true
