spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb_users
    username: dba
    password: psw01
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none #use existing database tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect